services:
  - type: web
    name: my-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free

  - type: web
    name: my-frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run front.py --server.port $PORT --server.address 0.0.0.0"
    plan: free
